name = "prisionero-frontend"
type = "javascript"
main = "index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "prisionero-pages"
routes = [
  { pattern = "prisionero.pages.dev", zone_name = "pages.dev" }
]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.jsx", "src/**/*.css"]

[build.upload]
format = "service-worker"

[env.production.build]
command = "npm run build"
cwd = "./"

[[routes]]
pattern = "*"
zone_name = "pages.dev"
